--- a/.github/workflows/cli_test.yml
+++ b/.github/workflows/cli_test.yml
@@ -40,4 +40,4 @@
         run: |
           go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
           go test -json ./... | gotestfmt 
-        working-directory: cli
+        working-directory: cli