--- a/.github/workflows/ee_cli_test.yml
+++ b/.github/workflows/ee_cli_test.yml
@@ -37,4 +37,4 @@
 
       - name: Test
         run: go test -v ./...
-        working-directory: ee/cli
+        working-directory: ee/cli